IMAGE_NAME = "ubuntu/jammy64"

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = IMAGE_NAME
    ubuntu.vm.hostname = "ubuntu"

    # Port forwarding pro SSH
    ubuntu.vm.network "forwarded_port", guest: 22, host: 2202, host_ip: "127.0.0.1"

    # Primární síť DHCP
    ubuntu.vm.network "private_network", type: "dhcp"

    # Druhá síť (intnet) s pevnou IP
    ubuntu.vm.network "private_network", ip: "192.168.1.3", virtualbox__intnet: true
  end

  # Spuštění instalačních skriptů
  config.vm.provision "shell", path: "install-zabbix-agent2.sh"
  config.vm.provision "shell", path: "configure-zabbix-agent2.sh"
end
